// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 7/3/2024, 12:31:39 PM
const configMerger = require("/Users/alfino/Desktop/vue-nuxt/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.mjs");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/alfino/Desktop/vue-nuxt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/alfino/Desktop/vue-nuxt/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/alfino/Desktop/vue-nuxt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/alfino/Desktop/vue-nuxt/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/alfino/Desktop/vue-nuxt/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/alfino/Desktop/vue-nuxt/plugins/**/*.{js,ts,mjs}","/Users/alfino/Desktop/vue-nuxt/composables/**/*.{js,ts,mjs}","/Users/alfino/Desktop/vue-nuxt/utils/**/*.{js,ts,mjs}","/Users/alfino/Desktop/vue-nuxt/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/alfino/Desktop/vue-nuxt/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/alfino/Desktop/vue-nuxt/app.config.{js,ts,mjs}"] }));

module.exports = config
